
datasource:
  db1:
    jdbc-url: jdbc:h2:file:./db1;AUTO_SERVER=TRUE;Mode=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  db2:
    jdbc-url: jdbc:h2:file:./db2;AUTO_SERVER=TRUE;Mode=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
